[default]
TITLE = "Rent Control"
DEBUG = false
DEBUG_TB_INTERCEPT_REDIRECTS = false
EXTENSIONS = [
    "rental.ext.database:init_app",
    "rental.ext.admin:init_app",
    "rental.ext.auth:init_app",
    "rental.ext.cli:init_app",
    "rental.ext.toolbar:init_app",
    "rental.ext.crypt:init_app",
    "rental.ext.search:init_app",
    "rental.ext.upload:init_app",
    "rental.blueprints.restapi:init_app",
    "rental.blueprints.webui:init_app",
]

[development]
DEBUG = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
SQLALCHEMY_DATABASE_URI = "sqlite:///rental.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false


[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false